apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatalyakpixelisticbe
  labels:
    app: gatalyakpixelisticbe  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatalyakpixelisticbe  
  template:
    metadata:
      labels:
        app: gatalyakpixelisticbe 
    spec:
      containers:
        - name: gatalyakpixelisticbe 
          image: pixelisticacr.azurecr.io/gatalyakpixelisticbe
          ports:
          - containerPort: 3000
