apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatalyakpixelisticbe
  labels:
    app: gatalyakpixelisticbe  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatalyakpixelisticbe  
  template:
    metadata:
      labels:
        app: gatalyakpixelisticbe 
    spec:
      containers:
        - name: gatalyakpixelisticbe 
          image: pixelisticacr.azurecr.io/gatalyakpixelisticbe
          ports:
          - containerPort: 3000
          env:
          - name: MONGO_DB
            value: "mongodb://admin:PassMongo@pixelistic.southcentralus.cloudapp.azure.com:27017/pixelapp"
